# Generated by Django 4.1.5 on 2023-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_test_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
