# Generated by Django 4.1.5 on 2023-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_botuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
