# Generated by Django 4.1.5 on 2023-01-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='app.test', unique=True),
        ),
    ]
